// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Recipe {
    from:   number;
    to:     number;
    count:  number;
    _links: RecipeLinks;
    hits:   Hit[];
}

export interface RecipeLinks {
}

export interface Hit {
    recipe: RecipeClass;
    _links: HitLinks;
}

export interface HitLinks {
    self: Self;
}

export interface Self {
    href:  string;
    title: Title;
}

export enum Title {
    Self = "Self",
}

export interface RecipeClass {
    uri:             string;
    label:           string;
    image:           string;
    source:          string;
    url:             string;
    shareAs:         string;
    yield:           number;
    dietLabels:      DietLabel[];
    healthLabels:    string[];
    cautions:        string[];
    ingredientLines: string[];
    ingredients:     Ingredient[];
    calories:        number;
    totalWeight:     number;
    totalTime:       number;
    cuisineType?:    string[];
    mealType?:       string[];
    dishType?:       string[];
    totalNutrients:  { [key: string]: Total };
    totalDaily:      { [key: string]: Total };
    digest:          Digest[];
}

export enum DietLabel {
    HighProtein = "High-Protein",
    LowCarb = "Low-Carb",
    LowSodium = "Low-Sodium",
}

export interface Digest {
    label:        Label;
    tag:          string;
    schemaOrgTag: SchemaOrgTag | null;
    total:        number;
    hasRDI:       boolean;
    daily:        number;
    unit:         Unit;
    sub?:         Digest[];
}

export enum Label {
    Calcium = "Calcium",
    Carbs = "Carbs",
    CarbsNet = "Carbs (net)",
    Cholesterol = "Cholesterol",
    Energy = "Energy",
    Fat = "Fat",
    Fiber = "Fiber",
    FolateEquivalentTotal = "Folate equivalent (total)",
    FolateFood = "Folate (food)",
    FolicAcid = "Folic acid",
    Iron = "Iron",
    Magnesium = "Magnesium",
    Monounsaturated = "Monounsaturated",
    NiacinB3 = "Niacin (B3)",
    Phosphorus = "Phosphorus",
    Polyunsaturated = "Polyunsaturated",
    Potassium = "Potassium",
    Protein = "Protein",
    RiboflavinB2 = "Riboflavin (B2)",
    Saturated = "Saturated",
    Sodium = "Sodium",
    SugarAlcohols = "Sugar alcohols",
    Sugars = "Sugars",
    SugarsAdded = "Sugars, added",
    ThiaminB1 = "Thiamin (B1)",
    Trans = "Trans",
    VitaminA = "Vitamin A",
    VitaminB12 = "Vitamin B12",
    VitaminB6 = "Vitamin B6",
    VitaminC = "Vitamin C",
    VitaminD = "Vitamin D",
    VitaminE = "Vitamin E",
    VitaminK = "Vitamin K",
    Water = "Water",
    Zinc = "Zinc",
}

export enum SchemaOrgTag {
    CarbohydrateContent = "carbohydrateContent",
    CholesterolContent = "cholesterolContent",
    FatContent = "fatContent",
    FiberContent = "fiberContent",
    ProteinContent = "proteinContent",
    SaturatedFatContent = "saturatedFatContent",
    SodiumContent = "sodiumContent",
    SugarContent = "sugarContent",
    TransFatContent = "transFatContent",
}

export enum Unit {
    Empty = "%",
    G = "g",
    Kcal = "kcal",
    Mg = "mg",
    Μg = "µg",
}

export interface Ingredient {
    text:         string;
    weight:       number;
    foodCategory: null | string;
    foodId:       string;
    image:        null | string;
}

export interface Total {
    label:    Label;
    quantity: number;
    unit:     Unit;
}
